dev_mode: false
version: "2.0.1"
Proxy :
    activate: true
    file: null #path to file, one proxy per line
    links:
        https://raw.githubusercontent.com/TheSpeedX/PROXY-List/master/http.txt : "http"
        https://raw.githubusercontent.com/monosans/proxy-list/main/proxies/http.txt: "http"
        https://raw.githubusercontent.com/TheSpeedX/SOCKS-List/master/socks5.txt : "socks"
        https://raw.githubusercontent.com/TheSpeedX/SOCKS-List/master/socks4.txt : "socks"
        https://raw.githubusercontent.com/ShiftyTR/Proxy-List/master/socks5.txt : "socks"
        https://raw.githubusercontent.com/ShiftyTR/Proxy-List/master/socks4.txt : "socks"
        https://raw.githubusercontent.com/ShiftyTR/Proxy-List/master/http.txt : "http"
        https://raw.githubusercontent.com/jetkai/proxy-list/main/online-proxies/txt/proxies-https.txt : "https"
        https://raw.githubusercontent.com/jetkai/proxy-list/main/online-proxies/txt/proxies-socks5.txt : "socks"
        https://raw.githubusercontent.com/jetkai/proxy-list/main/online-proxies/txt/proxies-socks4.txt : "socks"
        https://raw.githubusercontent.com/jetkai/proxy-list/main/online-proxies/txt/proxies-http.txt : "http"
        https://raw.githubusercontent.com/monosans/proxy-list/main/proxies/socks4.txt : "socks"
        https://raw.githubusercontent.com/monosans/proxy-list/main/proxies/socks5.txt : "socks"
    only_file: False
    get_workers: 50 #number of pool workers when request is made (you can set it to 1 if you have your own proxy list but free ones are most of the time down)

Handler :
    header: "User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36"
    params: Null

FQDN :
    find_subs : True #will try to get subs when FQDN from ip is found
    get_fqdn_trough_proxy: False #will try to get fqdn trough proxy (All API)
    get_from_cert : True #connection to target will be made during initial scan

IP :
    trough_proxy: False #will do all ip related task trough proxy
    try_get_fqdn: True #will try to get fqdn from ip

API :
    mapper :
        alienvault :
            activate : True
            api_key : null
        anubisdb :
            activate : True
            api_key : null
        certspotter :
            activate : True
            api_key : null
        crtsh :
            activate : True
            api_key : null
        hackertarget :
            activate : True
            api_key : null
        rapiddns :
            activate : True
            api_key : null
    trough_proxy: True
    max_workers: 2000

SCOPE :
    FQDNs :
        file: False # path to file, one ip or fqdn per line
        regex: False # regex to match example : ["example.com", "example.org", "^.*\.example\.com$"]
        list: False # list of ip or fqdn
    IPs :
        file: False # path to file, one ip or fqdn per line
        regex: False # regex to match
        list: False # list of ip or fqdn


TOOLS :
    AS_scan:
        brute_subs:
            file: "brute_subs"
            activate: true
            workers: 3000
            wordlist_name: "n0kovo_subdomains_tiny.txt"
            resolver_name: "resolvers.txt"
            recursive: true
    after_AS_scan:
        ports_scanner:
            file: "ports_scanner"
            activate: true
            workers: 2000
        detect_services:
            file: "detect_services"
            activate: true
            workers: 2000    
        analyze_web_techno:
            file: "analyze_web_techno"
            activate: true
            workers: 2000
        nuclei:
            file: "nuclei"
            headless_browser: false
            activate: true
            conf_file: null

WEB : #export
    activate : True
    metadata:
        depends_on : null
        style: "list"
        name: "Metadata"
        tab: "Metadata"
        mapper: "metadata"

    initial_scan:
        depends_on : null
        style: "table"
        collumns: ["IP","FQDNs"]
        name: "Attack Surface"
        tab: "IPs - FQDNs"
        mapper: "initial_scan"
    
    deads :
        depends_on : null
        style: "list"
        name: "Deads FQDNs"
        tab: "IPs - FQDNs"
        mapper: "deads"

    ports_scanner:
        depends_on : null
        style: "table"
        collumns: ["IP", "Ports"]
        name: "Ports & Services"
        tab: "Ports - Services"
        mapper: "return_ports"

    detect_services:
        collumns: ["Services"]
        depends_on : "ports_scanner"
        mapper: "return_services"

    analyze_web_techno:
        depends_on : null
        tab: "Web Technologies"
        name: "Web Technologies"
        style: "table"
        collumns: ["Url", "IP", "Technologies", "Version", "Headers"]
        mapper: "return_web_techno"
    
    nuclei:
        depends_on : null
        tab: "Vulnerabilities"
        name: "Nuclei"
        style: "table_multi"
        collumns: ["IP|FQDN", "Name", "Severity", "Cve-id", "Cwe-id", "Cvss-metrics", "Cvss-score", "Description", "Reference", "Type", "Host", "Matched-at", "Extracted-results", "Ip", "Timestamp", "curl-command", "matcher-status", "matched-line", "matcher-name", "Tags", "template", "template-url", "template-id", "template-path", "Author"]
        mapper: "return_nuclei"


UPDATE :
    - tools/wordlists/n0kovo_subdomains_tiny.txt: ["https://raw.githubusercontent.com/n0kovo/n0kovo_subdomains/main/n0kovo_subdomains_tiny.txt", "3:days" ] #seconds, minutes, hours, days
    - tools/wordlists/n0kovo_subdomains_small.txt: ["https://raw.githubusercontent.com/n0kovo/n0kovo_subdomains/main/n0kovo_subdomains_small.txt","3:days" ]
    - tools/wordlists/n0kovo_subdomains_medium.txt: ["https://raw.githubusercontent.com/n0kovo/n0kovo_subdomains/main/n0kovo_subdomains_medium.txt", "3:days" ]
    - tools/wordlists/n0kovo_subdomains_large.txt: ["https://raw.githubusercontent.com/n0kovo/n0kovo_subdomains/main/n0kovo_subdomains_large.txt", "3:days" ]
    - tools/wordlists/n0kovo_subdomains_huge.txt: ["https://raw.githubusercontent.com/n0kovo/n0kovo_subdomains/main/n0kovo_subdomains_huge.txt", "3:days" ]
    - tools/resolvers/resolvers.txt: ["https://raw.githubusercontent.com/trickest/resolvers/main/resolvers.txt", "30:minutes"]
